# .github/workflows/ping.yml
name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minuto
  workflow_dispatch:       # Permite correrlo manualmente también

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://mainomai.onrender.com
